### ISSUE TITLE
Support for sample weights in Double Machine Learning Estimators

### ISSUE THREAD

**Issue by vasilismsr** [microsoft/EconML#100]
When samples represent summary statistics of many observations, then we need to pass in weights and variance properties of each sample. This will affect model fitting and inference.

**Comment by kbattocchi** [comment]
@vasilismsr Is there anything needed for this other than what's already being added in #75?

**Comment by kbattocchi** [comment]
@vasilismsr  See also #26

**Comment by kbattocchi** [comment]
Closing since this is basically a duplicate of #26.
