### ISSUE TITLE
Reusing effect code during `_RLearner` scoring

### ISSUE THREAD

**Issue by vasilismsr** [microsoft/EconML#109]
In this line:
https://github.com/microsoft/EconML/blob/50baec376bd3b906b0f16720d3b97711acdcd98c/econml/dml.py#L170

Why don't we simply call effect(X, T0=0, T1=T_test_pred). This ought to return Y_test_res_pred directly.

**Comment by heimengqi** [comment]
@vasilismsr I tried to change my code based on your suggestion, but I realized that seems it doesn't work for discrete treatment. T1=T_test_res is always a continues variable, but the effect function will apply both T0 and T1 as discrete variables and transform(T1), which will throw an error.
