### ISSUE TITLE
Predictions

### ISSUE THREAD

**Issue by federiconuta** [microsoft/EconML#116]
Hi all,

building up on a previous comment, I am trying to estimate cross price elasticities of demand.
In this toy example, I have 133 products; P is the matrix of prices of each product except the i^th; X includes a dummy for individual fixed effects and Y is the quantity for product I:

```n_products = round(1341*(0.1))
P = np.zeros((n_products, n_years, n_products - 1))
for i in np.arange(n_products):
    for j in np.arange(n_years):
        P[i, j, :] = p[np.arange(n_products) != i, j]

Y = q.flatten() #flatten returns a copy of the array collapsed into one dimension; so having Y that is a 1340*frac (e.g. 134 = 1340*0.1) x 12, collapsing into one arrays will result into for instance a 1608 array (= 134 x 12)
X = X.reshape((n_products*n_years, n_products - 1)) # X.shape = (1608, 133)
P = P.reshape((n_products*n_years, n_products - 1)) # P.shape = (1608, 133)

est.fit(Y, P, X, None, inference='statsmodels')
cross_estimates = est.const_marginal_effect(np.eye(n_products-1)) #predictions
lower_cross, upper_cross  = est.const_marginal_effect_interval(np.eye(n_products-1), alpha=.05)
```

What is expected is a 133 x 133 matrix of cross price elasticities which is indeed my output.
I would like to obtain a confidence interval for each single coefficient (so 133 x 133 confidence intervals). Problems are the upper and lower bounds of confidence intervals which results to be equal and equal to the estimate: upper = lower = cross_estimates. Now, what I guess is that either I am inputting the wrong matrix np.eye(n_products-1) as test matrix or that I have too many parameters with respect to observations. Hence I was trying to build up a bootstrap estimate on my own in order to obtain a confidence interval for each one of the 133 x 133 estimates; but to do that I guess I need a predicted vale or something equivalent to est.predict() which I cannot find in the package. Can you, please help me find out a solution? :)

**Comment by vasilismsr** [comment]
You do not need a predict to get confidence intervals for the cross price elasticity matrix. Please check our code on the orange juice data here https://github.com/microsoft/EconML/blob/master/notebooks/Double%20Machine%20Learning%20Examples.ipynb

But again you have too few number of time steps for the type of analysis you want to perform.
