### ISSUE TITLE
Rework featurization in DML, add explicit intercept

### ISSUE THREAD

**Issue by kbattocchi** [microsoft/EconML#119]
There are a few issues with the way featurization works in the current version of our DML classes.  For example, given the default featurizer (which just adds a constant feature to the existing features to provide the equivalent of an intercept), if the user passes in None for X we end up with two constant columns (one because we treat no X as the same as a single constant feature and the other from the featurizer).

Instead, we should change the init parameters and their defaults:

1. We should add an explicit `fit_intercept=True` param independent of the featurizer; this will make it easier to present the results of fitting the model, and will additionally make it possible to do things like only shrink the the non-intercept weights when using Lasso (with some additional, separate, work)
2. Then we can make the default featurizer `None`, which will be easier to understand.  The user will be responsible for making sure that if they set the featurizer to something that includes a constant, that they switch `fit_intercept` to False.
3. When `X` is None and the featurizer is not None, we should warn the user and ignore the featurizer.

**Comment by heimengqi** [comment]
Also, when we compute the cross product (ϕ(x);w)⊗(x;w)) we end up with many identical columns (because w_1 * w_2 == w_2 * w_1, for example.  Can we avoid this?  Would it affect, say, confidence intervals?

**Comment by heimengqi** [comment]
Also, if W was generated by a polynomial featurizer, we'll have even more duplicates, because w_i^n*w_i^m is the same for many other combinations of n',m'.

**Comment by vasilismsr** [comment]
#174 addresses this
