### ISSUE TITLE
General Orthogonal Learner

### ISSUE THREAD

**Issue by vasilismsr** [microsoft/EconML#133]
We should create a more general orthogonal learner class that contains an abstraction of the structure of the `_RLearner` and which would also encompass the `DMLIV` classes. This would contain code for any learner that has the two stage form:
1) fit nuisance functions in a cross-fitting manner
2) fit a final stage model using the predicted nuisance quantities
3) predict the effect based on the final fitted model

@moprescu has implemented the `BaseOrthoForest` at such a level of versatility, so we can borrow parts of that structure.

**Comment by kbattocchi** [comment]
Is this closed by #132?

**Comment by vasilismsr** [comment]
Closing issue. Addressed in #132
