### ISSUE TITLE
DML Module documentation

### ISSUE THREAD

**Issue by vasilismsr** [microsoft/EconML#149]
The DML module documentation docstring:
https://github.com/microsoft/EconML/blob/2946201057ecd82cfd3cde92bf2f3ec31ae7bc3c/econml/dml.py#L6

Contains very little information. We should move a lot of the technical content from here:
https://github.com/microsoft/EconML/blob/master/doc/spec/estimation/dml.rst
To this docstring.

**Comment by kbattocchi** [comment]
@vasilismsr Is this fully addressed by #159?

**Comment by vasilismsr** [comment]
Yeap
