### ISSUE TITLE
import error 

### ISSUE THREAD

**Issue by anaveenan** [microsoft/EconML#154]
I have pip installed econml . Getting an error when importing LinearDMLCateEstimator from ecnoml.dml 

cannot import name 'LinearDMLCateEstimator' from 'econml.dml'

Is there anything I am missing

```
import econml
## Ignore warnings
import warnings
warnings.filterwarnings('ignore')


# Main imports
from econml.dml import DMLCateEstimator, LinearDMLCateEstimator,SparseLinearDMLCateEstimator  
```

**Comment by vasilismsr** [comment]
LinearDMLCateEstimator is a class that only exists in the version from the git repo, not the pip installable one. To use the class you would need to reinstall from the git repo's version:
`git clone git@github.com:microsoft/EconML`

`cd EconML`

`python setup.py develop`

See also the instructions in the README of how to install from the git clone:
https://github.com/microsoft/EconML/tree/vasilis/cate_interpreters#for-developers

**Comment by kbattocchi** [comment]
Vasilis is right; however we hope to have another public release within the next week or so, so you can also just wait until then and upgrade your econml installation at that time.

**Comment by anaveenan** [comment]
Thanks for the quick update.
