### ISSUE TITLE
TensorFlow 1.* requirement

### ISSUE THREAD

**Issue by arose13** [microsoft/EconML#241]
This requirement is really ruining all of my builds. Especially since basically no part of this package uses Tensorflow

It would be easy for me to upgrade to TensorFlow version 2 while being backwards compatible. May I do a PR for this?

Cheers

**Comment by kbattocchi** [comment]
By all means, please feel free to submit a PR for this if it's easy to maintain compatibility.

**Comment by kbattocchi** [comment]
Addressed by #210
