### ISSUE TITLE
Reproducibility of treatment effects with random forest and honest trees in  final model

### ISSUE THREAD

**Issue by Chandrak1907** [microsoft/EconML#252]
I appreciate your great work. I am trying to use random forest and honest trees to estimate treatment effect by specifying 'random_state' argument. However, I get different results in each iteration. 

Working example with data given in ''Double Machine Learning Examples.ipynb'  is [here.](https://gist.github.com/Chandrak1907/495ce8d29e22f4f61d9cb4cb9515ddfb#file-double-machine-learning-examples-ipynb)

And for my specific use case, results differ a lot in each iteration.  So, I am curious to know how to trust the treatment effect results.

**Comment by kbattocchi** [comment]
Thanks for the very clear bug report, we'll take a look.

**Comment by Chandrak1907** [comment]
models can be saved now.
