### ISSUE TITLE
Best practice to follow in absence of true treatment effect

### ISSUE THREAD

**Issue by Chandrak1907** [microsoft/EconML#253]
I get different results for treatment effects with different methods. Below is a sample of dollar saving estimates.  How to evaluate the treatment effect results, when such variation is observed? Is there any best practice to follow?

T Learner | S Learner | X learner | Doubly Robust Learner | Double ML
-- | -- | -- | -- | --
1,355.8 | 688.1 | 1,037.7 | 1,173.5 | 242.8
736.7 | 702.6 | 286.1 | 475.6 | -429.9
-7,927.4 | -3,652.8 | -6,259.0 | -5,752.7 | 416.8
-1,998.8 | -942.0 | -1,764.5 | -1,884.0 | -291.6
-1,741.9 | -1,227.2 | -1,556.9 | -1,007.5 | -600.2

**Comment by vsyrgkanis** [comment]
DML assumes that the treatment effect is constant across your population, while the rest of the methods do not assume that and average a heterogeneous effect and present the average of this heterogeneous effect. 

Given that all the first few methods are more or less in line (I would mostly look at X learner and DR learner as the other methods are less robust and more prone to bias), I would say that your setup has heterogeneity in the effect and the X learner and the DR are doing the right thing, while DML is doing the wrong thing.

Also it is important to also look at confidence intervals. Are these numbers also confident numbers or just random variables. LinearDRLearner and LinearDML automatically provide confidence intervals via `inference=statsmodels`.

For the other methods you could try `inference=bootstrap`, though this would be slow.

**Comment by Chandrak1907** [comment]
Thank you for the detailed reply.  Sample table is from results of 'effect' function on learners.

Reasons for ambiguity in my use case are:

1. Single tree interpretation of DML model is more intuitive  and acceptable to business compared to other learners. 

2. Summary stats of results from three learners is below. Standard deviation of DML results is less and it makes more business sense. 


  | X-Learner | Doubly Robust | DML
-- | -- | -- | --
count | 2,561 | 2,561 | 2,561
mean | 149 | 82 | 88
std | 3,048 | 5,534 | 363
min | -9,594 | -75,711 | -1,047
25% | -967 | -1,028 | -187
50% | 54 | 96 | 108
75% | 1,009 | 1,189 | 350
max | 71,541 | 126,372 | 1,241

3. However as you mentioned DML might be doing wrong thing, because results from this are biased towards to a particular class.
