### ISSUE TITLE
'coef__inference'

### ISSUE THREAD

**Issue by Chandrak1907** [microsoft/EconML#257]
I am trying to understand 'coef__inference' of LinearDMLCateEstimator.  

Is the output of 'coef__inference' (with coefficients and p-values) another model fitted on 'predicted treatment effects' against observable characteristics 'X'?

**Comment by kbattocchi** [comment]
No, there's no extra model.  This is just providing extra information about the coefficients estimated by the final model, allowing you to view confidence intervals around the coefficients themselves (or get p-values for them, etc.).  Does that help?

**Comment by Chandrak1907** [comment]
Isn't the final model, a regression of 'residuals of Y' against 'residuals of T'?

**Comment by kbattocchi** [comment]
Almost; it's a regression of the residuals of Y against (residuals of T crossed with featurized Xs).  And so the `coef_` property lets you see the coefficients of this regression, and `coef__inference` lets you learn more about the distribution of these coefficients (under a normality assumption).

**Comment by Chandrak1907** [comment]
Can you pls share the link to equation for doing this (residuals of T crossed with featurized Xs)  in documentation (on https://econml.azurewebsites.net)?  I appreciate your help.

**Comment by vsyrgkanis** [comment]
Here it is:
https://econml.azurewebsites.net/spec/estimation/dml.html#class-hierarchy-structure
Check out the equation in the first bullet.
