### ISSUE TITLE
Which estimator is implemented in LinearDMLCateEstimator ?

### ISSUE THREAD

**Issue by aflatoune** [microsoft/EconML#265]
Dear all,

During my research on the DML method, I came across the following  set of slides : 
https://scholar.princeton.edu/sites/default/files/bstewart/files/felton.chern_.slides.20190318.pdf

page 40 (133/170), the authors discuss the use of an alternative estimator for the `\theta` parameter relying on Frisch-Waugh theorem (let's call it FW DML). As I understand it, this alternative estimator corresponds to the estimator described in footnote 4 of the original paper (https://arxiv.org/pdf/1608.00060.pdf, page 4), which is different from the estimator described in equation (1.5) of the original paper (page 4). 
My question is simple : which one of the two estimator is implemented in `LinearDMLCateEstimator` and why ?

Based on the following simulations, it appears that the two estimators are indeed different. For `LinearDMLCateEstimator`, we cannot compare the results with those of the two others estimators since the internal split of the `Y`, `T` and `W` is certainly not the same, but the predictions are very close to the predictions of the FW DML estimator.

Please do not hesitate to report errors in my code if there are any (especially for the estimation of `theta` using equation (1.5))

```
import numpy as np
import pandas as pd
import math
import statsmodels.api as sm
from statsmodels.stats.moment_helpers import cov2corr
from sklearn.datasets import make_spd_matrix
from sklearn.ensemble import RandomForestRegressor


def generate_data(N=500, k=50, true_theta=1) :

    b = [1/i for i in range(1,k+1)]
    
    #Generate  W:
    sigma = make_spd_matrix(k)
    sigma = cov2corr(sigma)
    W = np.random.multivariate_normal(np.ones(k), sigma, size=[N,])
    
    #apply g() and m() to b*W:
    g = np.power(np.cos(np.dot(W,b)),2)
    m = np.sin(np.dot(W,b))+np.cos(np.dot(W,b))
    
    #Generate  T:
    T = m + np.random.standard_normal(size=[N,])
    
    #Generate Y:
    Y = np.dot(true_theta,T) + g + np.random.standard_normal(size=[N,])
    
    return Y, T, W
```

```
def double_ml(Y, T, W, model_y=RandomForestRegressor(), model_t=RandomForestRegressor()):
    
    #Split :
    I = np.random.choice(Y.shape[0],np.int(Y.shape[0]/2),replace=False)
    IC = [x for x in np.arange(Y.shape[0]) if x not in I]

    #Estimate E[Y|W] :
    ghat_1 = model_y.fit(W[I],Y[I]).predict(W[IC]) #On entraine sur I, prédit sur IC
    ghat_2 = model_y.fit(W[IC],Y[IC]).predict(W[I]) #On entraine sur IC, prédit sur I
    
    #Estimate E[T|W] :
    mhat_1 = model_t.fit(W[I],T[I]).predict(W[IC]) #On entraine sur I, prédit sur IC
    mhat_2 = model_t.fit(W[IC],T[IC]).predict(W[I]) #On entraine sur IC, prédit sur I
    
    #Retrieve residuals :
    uhat_1 = Y[IC] - ghat_1
    uhat_2 = Y[I] - ghat_2
    vhat_1 = T[IC] - mhat_1
    vhat_2 = T[I] - mhat_2
    
    #Regress uhat on vhat to get FW DML coef :
    theta_1 = np.mean(uhat_1*vhat_1)/np.mean(vhat_1**2)
    theta_2 = np.mean(uhat_2*vhat_2)/np.mean(vhat_2**2)
    theta = 0.5*(theta_1+theta_2)
    
    #Compute the coef using equation (1.5) of the original paper :
    theta_1_bis = np.mean(vhat_1*uhat_1)/np.mean(vhat_1*T[IC])
    theta_2_bis = np.mean(vhat_2*uhat_2)/np.mean(vhat_2*T[I])
    theta_bis = 0.5*(theta_1_bis+theta_2_bis)

    return theta, theta_bis
```

```
n_sim = 100
theta_est = np.zeros(shape=[n_sim,3])
seed = 123
est=LinearDMLCateEstimator(model_y=RandomForestRegressor(n_estimators=10, random_state=seed), 
                           model_t=RandomForestRegressor(n_estimators=10, random_state=seed), 
                           fit_cate_intercept=True, 
                           n_splits=2)

np.random.seed(seed)
for i in range(n_sim):
    
    print(i)
    
    Y,T,W = generate_data(N=1000)
    
    #Frisch-Waugh DML :
    theta_est[i][0] = double_ml(Y, T, W, model_y=RandomForestRegressor(n_estimators=10, random_state=seed),
                                model_t=RandomForestRegressor(n_estimators=10, random_state=seed))[0]
    
    #DML (equation 1.5 of the paper) :
    theta_est[i][1] = double_ml(Y, T, W, model_y=RandomForestRegressor(n_estimators=10, random_state=seed),
                                model_t=RandomForestRegressor(n_estimators=10, random_state=seed))[1]
    
    #EconML DML
    theta_est[i][2] = est.fit(Y=Y, T=T, X=None, W=W).effect()
```

```
print(theta_est.mean(axis=0))
[0.93591228 1.03866621 0.93233801]
```

Thank you !

**Comment by vsyrgkanis** [comment]
We implement the partialling out version in the footnote. See also here for more information:
https://econml.azurewebsites.net/spec/estimation/dml.html#overview-of-formal-methodology

**Comment by aflatoune** [comment]
Thanks for the clarification. Is there any theoretical or practical justification for favouring this approach?

**Comment by vsyrgkanis** [comment]
The main reason we favored this approach is that the final stage estimator can also be thought as a regression estimator. 

Thus it can be heavily extended beyond a linear regression estimate. This allows us the full flexibility of the DMLCateEstimator, where any penalized linear regression can be used in the final stage. Or the ForestDMLCateEstimator, where a regression forest is used as a final stage, or the SparseLinearDMLCateEstimator, where a debiased lasso is used as a final stage. 

The other estimator, does have the property that the final stage can be thought of as a regression and does not allow the latter flexibility. 

It is true that for the specific case of the LinearDMLCateEstimator, we can easily exchange the final stage with the alternative estimate given in Chernozhukov et al. 

However, both scores are first order equivalent and hence have similar asymptotic efficiency properties.

Moreover, the extra weirdness of the other moment described in the intro of Chernozhukov et al, is that the nuisance function g_0 is weird to estimate generically. Estimating g_0 does not correspond to a black box regression problem. One would instead need to estimate a linearly separable model theta*D + g_0(X), where the treatment D enters additively and linearly. This is hard to do, if say one wants to estimate g_0 with a random forest.  Instead, the nuisance functions that are required in the other moment both are simply regression or classificaiton problems (see our documentation). So any ML model can be easily plugged in to solve them.
