### ISSUE TITLE
can not install econml for  tensorflow 2 support

### ISSUE THREAD

**Issue by zjyyysj** [microsoft/EconML#284]
can not install econml for 'Could not find a version that satisfies the requirement tensorflow==1.*'
can it support  tensorflow2?

**Comment by kbattocchi** [comment]
Tensorflow 2 support has been added in the beta for our upcoming release.  Could you try adding the `--pre` flag to your pip command line to enable installing prerelease versions?

**Comment by kbattocchi** [comment]
Closing since this has been addressed by our 0.8.0 release.
