### ISSUE TITLE
Exogenous variables for DMLIV

### ISSUE THREAD

**Issue by federiconuta** [microsoft/EconML#292]
Hi all,

so I would like to summarize the issue as follows.
Let's call SparseLinear case for CATE, B and IV the Ortho-IV (DMLIV) case.

In B the fit is made on Y (n,dy), T (n,dt), X (n,dx), W (n,dw). As pointed out in. previous issues, for a panel estimation, X includes group effects for each country/group as follows: `X = X[:, :(n_products)]` in an (n,n_groups). On the other hand, W includes the other features. Hence, when I am going to estimate CATE with const_marginal-effect I give as X_test to the latter command an (m, dx) matrix of samples. Now, in case B, I can give an (n_groups, n_groups) identity matrix to obtain an (n_groups, nt) matrix (which makes sense since I would like to obtain own and cross elasticities for each country).

In IV case, the situation changes. The fit ins made on Y (n,dy), T (n,dt), Z(n,dz), X (n,dx). I aam supposing that Z, as usual takes on all the exogenous variables + the instrument. The doubt is the following: if, as in case B, to obtain the CATE (i.e. (n_groups, nt) or own and crosses for each country) I have to insert an (n_groups, n_groups) identity matrix, it means that the X matrix has to have n_groups as second dimension (was in case B). The question now is: where do I put the exogenous variables which were in W in case B? I can include them in Z for sure, but I do not understand if the variables that I put in Z are automatically recognized as "exogenous variables" having an effect also on Y or all as instruments (and so not having a direct effect on Y)

Can you please clarify this last point?

Thank you very much

Federico

**Comment by kbattocchi** [comment]
For all of our estimators, Z includes only instruments, not any additional controls.  DMLIV does not currently support controls, but it should probably be straightforward for us to extend the class to support them.

**Comment by federiconuta** [comment]
Thank you @kbattocchi !

**Comment by kbattocchi** [comment]
This was addressed by #460, included in our v0.12 release
