### ISSUE TITLE
Shap interpretability with SubsampledHonestForest

### ISSUE THREAD

**Issue by vsyrgkanis** [microsoft/EconML#297]
The subsampled honest forest currently is not exactly compatible with Shap, due to some internal re-workings, even though it inherits from sciki-learn's random forest regressor. Thus getting Shap values for the learned model is not trivial. We should enable shap interpretability of the subsampled  honest forest, so that we can interpret ForestDML, ForestDRLearner and ForestDRIV.

**Comment by heimengqi** [comment]
I will take this.
