### ISSUE TITLE
check_high_dimensional - 'Series' object has no attribute 'flatten'

### ISSUE THREAD

**Issue by mohitjaggi** [microsoft/EconML#298]
When I switched from DR Learner (which was working fine) to SparseLinearDR, I got this. It seems that the function check_high_dimensional is only called for the sparse code path. Is this a bug? Any idea how to work around this?
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-effd21ddae70> in <module>
     54     treatment_train = X_train['treatment_flag']
     55     for learner_type, trainer in trainers.items():
---> 56         learner_trained = trainer(y_train, treatment_train, X_train)
     57         models[learner_type][term] = learner_trained

<ipython-input-7-5472dbcf3a5b> in rLearnerTrain(y_train, treatment_train, X_train)
      5     DR_learner = SparseLinearDRLearner()
      6     # Train DR_learner
----> 7     DR_learner.fit(y_train, treatment_train, X_train.drop('treatment_flag', 1))
      8     return DR_learner

/dsw/snapshots/snapshot_dsw_default_jupyter/python3/lib/python3.6/site-packages/econml/drlearner.py in fit(self, Y, T, X, W, sample_weight, sample_var, inference)
    889         check_high_dimensional(X, T, threshold=5, featurizer=self.featurizer,
    890                                discrete_treatment=self._discrete_treatment,
--> 891                                msg="The number of features in the final model (< 5) is too small for a sparse model. "
    892                                "We recommend using the LinearDRLearner for this low-dimensional setting.")
    893         return super().fit(Y, T, X=X, W=W, sample_weight=sample_weight, sample_var=None, inference=inference)

/dsw/snapshots/snapshot_dsw_default_jupyter/python3/lib/python3.6/site-packages/econml/utilities.py in check_high_dimensional(X, T, threshold, featurizer, discrete_treatment, msg)
     69         d_x = clone(featurizer, safe=False).fit_transform(X[[0], :]).shape[1]
     70     if discrete_treatment:
---> 71         d_t = len(set(T.flatten())) - 1
     72     else:
     73         d_t = 1 if np.ndim(T) < 2 else T.shape[1]

/dsw/snapshots/snapshot_dsw_default_jupyter/python3/lib/python3.6/site-packages/pandas/core/generic.py in __getattr__(self, name)
   5177             if self._info_axis._can_hold_identifiers_and_holds_name(name):
   5178                 return self[name]
-> 5179             return object.__getattribute__(self, name)
   5180 
   5181     def __setattr__(self, name, value):

AttributeError: 'Series' object has no attribute 'flatten'

**Comment by vsyrgkanis** [comment]
This seems related to pandas vs numpy. Currently our package can only support numpy arrays as input. Try passing df.values instead of df as input.

**Comment by mohitjaggi** [comment]
that works
