### ISSUE TITLE
Logic in summary_frame

### ISSUE THREAD

**Issue by vsyrgkanis** [microsoft/EconML#303]
The logic here:
https://github.com/microsoft/EconML/blob/a1d6aa81b512e2312a08fecac849db8cbbea03b9/econml/inference.py#L640

might be better in terms of user experience to change slightly. In particular, cate_feature_names can handle None feat_names as input and do something fancy even when feat_names is None (e.g. returning the metadata info or the featurizer's output (which can also accept None). 

So if fname_transformer is not None, we should always call it as fname_transformer(feat_name), even if feat_name is None. 

Moreover, if fname_transformer is None, but feat_name is not None, then we should use the raw feat_names as feature names without transforming them.

**Comment by vsyrgkanis** [comment]
Fixed by #305

**Comment by shrabasteebanerjee** [comment]
Wanted to point out a small thing related to this in case someone runs into a similar issue: following the DRLearner notebook, I was trying to pass "feature_names" to summary_frame() which it did not recognise. Then I explicitly imported InferenceResults from econml.inference, and discovered the feat_name input!
