### ISSUE TITLE
Get first stages residuals

### ISSUE THREAD

**Issue by gcasamat** [microsoft/EconML#321]
Hi, 
I am training a linear dml cate estimator and I need to access the first stages residuals of the outcome and treatment variables that are being used in the final stage. Is there a simple way to get these residuals ? 
Thanks a lot!

**Comment by vsyrgkanis** [comment]
Thats not implemented unfortunately. Residuals are currnetly discarded after fit. Original design was to avoid keeping large datasets in the classes state.

Though a new PR we are preparing will store residuals and also allow changing the final stage model and only fitting the final stage with the already computed residuals.

This would then make residuals available and will also enable further interpretability based on influential points etc

**Comment by raylinz** [comment]
@vsyrgkanis Thanks for the above update that's great news! Curious is there a rough ETA to launch this new PR/feature that outputs residuals from the T~ predictor & Y~ predictor?

**Comment by kbattocchi** [comment]
@raylinz This is available in our 0.9.0b1 beta (which you should be able to get via `pip install econml -U --pre`) - #360 is where the changes were made.  See also our release notes [here](https://github.com/Microsoft/EconML/releases/tag/v0.9.0b1) - there are several breaking changes in this release.

We're hoping to have the final 0.9.0 release out in a few days, which will have these changes plus a few additional bug fixes and improvements.

**Comment by kbattocchi** [comment]
@gcasamat As I mentioned in the previous comment, this is now possible when using our latest beta release, so I'm closing this issue.  See the documentation for the [`residuals_`](https://econml.azurewebsites.net/_autosummary/econml.dml.DML.html#econml.dml.DML.residuals_) attribute - it will contain a tuple of the Y and T residuals as well as the X and W that were used to fit (although possibly in a different order than the original data).

**Comment by raylinz** [comment]
Thanks a lot @kbattocchi! Let me try it

**Comment by kbattocchi** [comment]
In case you haven't seen, our v0.9.0 release is now out, so you no longer need to use `--pre` when installing.

**Comment by raylinz** [comment]
Hi @kbattocchi - qq on `DML.residuals_`: the documentation says "Samples are not guaranteed to be in the same order as the input order." Is there a way to get to know which residual (from the output of `DML.residuals_`) is associated with which training data point (sample)? I'm using the latest v0.9.0 release. Thanks!
