### ISSUE TITLE
plotting the residuals T & Y from the model

### ISSUE THREAD

**Issue by skfkrh** [microsoft/EconML#350]
Is there any way I can plot the residuals of T and Y after fitting?
Trying to see how residuals look like to get better sense of data in addition to MSE I can get.
Thank you!

**Comment by vsyrgkanis** [comment]
A way of accessing residuals should be available in the upcoming beta release in the next few days. Currently the estimator does not store the results of the first stage (to keep the object lightweight) so there is no way to access that. But we'll enable a flag that allows you to store these values and access them later on and also refit a different final stage model. See the PR #343 for more details.

**Comment by skfkrh** [comment]
Awesome! great!

**Comment by skfkrh** [comment]
Could you actually write some example script to fetch it once it's done?
Or at least if you add some description of that function in https://econml.azurewebsites.net/
that'd be great!

**Comment by skfkrh** [comment]
Also, is there any way I can plot one iteration of the bootstrapped values to generate CI?
I just want to see how it's distributed, if it's normal or sth like that.
