### ISSUE TITLE
EconML incompatible with sklearn 0.24

### ISSUE THREAD

**Issue by jaronowitz** [microsoft/EconML#379]
A few EconML classes depend on `sklearn.ensemble.forest` module which is deprecated in version 0.22 and is removed in version 0.24. During install though `sklearn<0.24` does not seem to be a requirement.

**Comment by vsyrgkanis** [comment]
That has been fixed in our latest release (which now actually requires 0.24); though most things will also work with smaller versions too.

check out via
pip install -U —pre econml

put the pre because the latest release is a beta. We’ll push a non beta in abiut a week.

**Comment by jaronowitz** [comment]
Great, thanks for the response
