### ISSUE TITLE
Installation problem?

### ISSUE THREAD

**Issue by JuergenKanz** [microsoft/EconML#394]
I installed DoWhy, CausalML, and EconML on my Windows 10 PC with "pip install" in my Anaconda3 environment. Unfortunately, EconML can not find all kinds of subelements like econml**.orf** or econml**.dml**. Attached an example.

![Screenshot 2021-02-02 121131](https://user-images.githubusercontent.com/65070344/106594328-3cfefe80-6552-11eb-95c8-26cbf44373c7.png)

What can I do?

**Comment by vsyrgkanis** [comment]
Sorry for this! The notebooks have been updated to work with the 0.9b pre-release we've pushed on pypi, but not the older 0.8.1 release. 

To make the new notebooks work you can install with the --pre option, i.e. pip install --pre econml -U

This will install the 0.9b pre-release. 

We'll soon (in a week) have a formal 0.9 release which would avoid the problem you faced.

**Comment by JuergenKanz** [comment]
Okay, Thank you!
