### ISSUE TITLE
Creating copies of pred and pred_stderr in inference results

### ISSUE THREAD

**Issue by vsyrgkanis** [microsoft/EconML#402]
It's better that we copy the `pred` attribute in the line below. This way the pred attribute of the inference results is not linked to the memory space of where it originated from. It seems weird behavior to change the pred attribute of inference results and alter the parameter of the estimator from where it stemmed from. So we should "detach" it:

https://github.com/microsoft/EconML/blob/3e66b9507b43f8af291009d26186283fa4bb4ced/econml/inference/_inference.py#L545

Similarly the `pred_stderr`:
https://github.com/microsoft/EconML/blob/3e66b9507b43f8af291009d26186283fa4bb4ced/econml/inference/_inference.py#L833

and the `pred_dist`:
https://github.com/microsoft/EconML/blob/3e66b9507b43f8af291009d26186283fa4bb4ced/econml/inference/_inference.py#L933

**Comment by heimengqi** [comment]
Sure, this one will be fixed in PR #407 as well. However, change the `pred` attribute from InferenceResults object will not change any parameter of the estimator in practice? it's just by definition we should "detach" them?

**Comment by heimengqi** [comment]
I had a discussion with @kbattocchi on this and we don't think we really need to add copy here. First of all, given the way we initialize the inference results, modify the inference object's attribute will not propagate to the estimator's attribute. Second of all, it will use some amount of memory for no gain. 

So I undo the changes on my PR, @vsyrgkanis  let me know if you have other reasons you think this is required.

**Comment by vsyrgkanis** [comment]
I encountered this error, which is why I thought would be good to make copies. 

When I am calling: `coef__inference()` and then I go and change the inference results point estimate, then this will go and change the `coef_` of the original estimator. So
```python
est = LinearDML().fit(y, T, X=X)
print(est.coef_)
inf = est.coef__inference()
inf.pred[0] = .5
print(est.coef_)
```
Then this will print .5 in the second time and that feels weird. Why would changing sth in the inference results change the coefficient in the original model?

Similar thing happens with `intercept__inference`.

**Comment by heimengqi** [comment]
Weird, there is no direct way could pass from `inf.pred` to `est.coef_`, and add copy on those inference attribute do solve this issue.

I tried with a vanilla example, but it doesn't propagate in a way like InferenceResults...


```
class A:
    def __init__(self,a):
        self.a=a
    def func(self):
        return B(self.a)

class B:
    def __init__(self,b):
        self.b=b
        
est_a=A(3)
inf=est_a.func()
print(est_a.a)
inf.b=5
print(inf.b)
print(est_a.a)
```

**Comment by vsyrgkanis** [comment]
That doesn't happen with floats. But happens with numpy array attributes that are fixed memory spaces.

**Comment by heimengqi** [comment]
Oh yeah that's true, Okay I will add it back in a new PR.
