### ISSUE TITLE
Incorporation with SHAP

### ISSUE THREAD

**Issue by jlevy44** [Microsoft/EconML#41]
SHAP is a popular new model interpretability method. Seems to be gaining a lot of traction. Are there plans to incorporate these causal estimates with model agnostic interpretations? Purely out of curiosity, with only having read a little of your work

**Comment by kbattocchi** [comment]
@jlevy44 I see that you've closed this issue, but just to let you know, we're planning on taking a closer look at various methods for interpretability over the next few months.  It's not clear yet whether we'll incorporate specific methods or provide the ability to plug in different methods (or build estimator-specific interpretability tools), but we'll definitely consider SHAP once we get started.  Thanks.
