### ISSUE TITLE
ModuleNotFoundError: No module named 'econml.dr'

### ISSUE THREAD

**Issue by drmingle** [microsoft/EconML#410]
I tried to run this on my local and Google Colab, both provided the same error.

I am simply trying to run an example in your documentation:

```
from econml.dr import LinearDRLearner
from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier

est = LinearDRLearner(model_propensity=GradientBoostingClassifier(),
                      model_regression=GradientBoostingRegressor())
est.fit(Y, T, X=X, W=W)
treatment_effects = est.effect(X_test)
lb, ub = est.effect_interval(X_test, alpha=0.05)
```
Traceback below:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-4-ba84eeb7de65> in <module>()
----> 1 from econml.dr import LinearDRLearner
      2 from sklearn.ensemble import GradientBoostingRegressor, GradientBoostingClassifier
      3 
      4 est = LinearDRLearner(model_propensity=GradientBoostingClassifier(),
      5                       model_regression=GradientBoostingRegressor())

ModuleNotFoundError: No module named 'econml.dr'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
```
---------------------------------------------------------------------------

Any help would be appreciated.

**Comment by kbattocchi** [comment]
Apologies, we updated our documentation to reflect the latest version of our package (v0.9.0b1), which is a prerelease (should be available from PyPI via `pip install econml -U --pre`). The production version of this release should come out in a day or two.  In this release we’ve relocated some of our estimators to be more consistent, but added aliases to allow using the deprecated former locations. However the documentation only covers the new locations. Sorry for the inconvenience.

**Comment by drmingle** [comment]
@kbattocchi No worries. Your suggestion worked for me. Thank you for being so responsive.
