### ISSUE TITLE
ForestDRLearner DoWhy Fit not working

### ISSUE THREAD

**Issue by jbel1026** [microsoft/EconML#432]
Hello,
I am trying to implement forestdrlearner.dowhy.fit() and it is throwing a recursion error, this method has been working on all other econml estimators. Is this a known issue? Can this be looked into? 
The propensity and regression models are both XGBoost 
I am using econml V. 0.9.2

![image](https://user-images.githubusercontent.com/80842968/111528510-9ce2ea80-8737-11eb-9d6f-1081555be205.png)

**Comment by jbel1026** [comment]
Additonally, I get a different error when trying to refute the estimate using the DoWhyWrapper
thanks!
![image](https://user-images.githubusercontent.com/80842968/111673771-b183b900-87f1-11eb-8157-8a1e93bcfed0.png)

**Comment by heimengqi** [comment]
Hi @jbel1026 , thanks for reaching out! I am working on fixing the first issue you are raising, that's related to our deprecated args in `ForestDRLearner`, I will have PR solving this issue today. 

For the second one, are you using `DRLearner`?

**Comment by jbel1026** [comment]
Hello @heimengqi , thanks so much for the quick reply with this, both examples are using the `ForestDRLearner`

**Comment by heimengqi** [comment]
I see, since you didn't fit successfully with `ForestDRLearner`, you can't call `refute_estimate` then, you should do it in a sequential way.

**Comment by jbel1026** [comment]
@heimengqi I figured as much, thanks!

**Comment by jbel1026** [comment]
@heimengqi Thanks for all your help, should I be able to run this now by just reinstalling V0.9.2 and running the commands?

**Comment by heimengqi** [comment]
We just released V0.10.0 yesterday, which included this fix. Please upgrade to the new version, it will solve this issue. Thanks!
