### ISSUE TITLE
keras backend 

### ISSUE THREAD

**Issue by yangyang2000** [microsoft/EconML#443]
keras version 2.4.3
tf version 2.4.1
AttributeError: module 'keras.backend' has no attribute 'logsumexp'

K.logsumexp is no longer in keras.backend?  runs when i replace with K.log(K.sum(K.exp...), axis =-1)) though other issues arise.

**Comment by kbattocchi** [comment]
Yes, annoyingly Keras 2.4 is not backwards compatible with Keras 2.3, which is why our current dependencies are:
```
    keras < 2.4
    tensorflow > 1.10, < 2.3
```

See also #352, which will be fixed once #389 is completed.

**Comment by yangyang2000** [comment]
I see, thanks!
