### ISSUE TITLE
ImportError: cannot import name 'LinearDML' from 'econml.dml' 

### ISSUE THREAD

**Issue by MJeremy2017** [microsoft/EconML#449]
I am following the examples on the doc and failed when executing
```
from econml.dml import LinearDML
```
Which gave me the error
```
ImportError: cannot import name 'LinearDML' from 'econml.dml'
```

I have my `sklearn` and `econml` installed as
```
pip install scikit-learn==0.21.0
pip install econml
```

Can anyone shed light on it? thanks in advance.

**Comment by kbattocchi** [comment]
What version of python and econml are you using?  In recent versions of econml you can determine this via `import econml; print(econml.__version__)`, but for older versions you can check via `pip list`.

**Comment by MJeremy2017** [comment]
> What version of python and econml are you using? In recent versions of econml you can determine this via `import econml; print(econml.__version__)`, but for older versions you can check via `pip list`.

My version is `econml==0.7.0`

**Comment by kbattocchi** [comment]
I see, that release is over a year old and we've reorganized our namespaces and classes a bit since then.  What version of Python are you using?  If it's at least Python 3.6, then it should be possible to upgrade via `pip install -U econml`.  If that's not possible, then in the release you're using, the class is called `econml.dml.LinearDMLCateEstimator`, but note that we've made many improvements to the package since that time.

**Comment by MJeremy2017** [comment]
> I see, that release is over a year old and we've reorganized our namespaces and classes a bit since then. What version of Python are you using? If it's at least Python 3.6, then it should be possible to upgrade via `pip install -U econml`. If that's not possible, then in the release you're using, the class is called `econml.dml.LinearDMLCateEstimator`, but note that we've made many improvements to the package since that time.

Hi, I think this is the problem, looks like my `pip install` would look into an on-premise index, in which there is only an elder version of econml.

I tried to specify index when installing
```
pip install --index-url https://pypi.org/project/ econml
```
But got error
```
Looking in indexes: https://pypi.org/project/
Collecting econml
Using cached econml-0.10.0-cp37-cp37m-manylinux2010_x86_64.whl (3.0 MB)
ERROR: Could not find a version that satisfies the requirement shap~=0.38.1 (from econml)
ERROR: No matching distribution found for shap~=0.38.1
```

Does this mean I need to manually install other dependences? Any workarounds?

**Comment by MJeremy2017** [comment]
fixed with
```
pip install --index-url https://pypi.python.org/simple econml
```
