### ISSUE TITLE
Causal Inference 

### ISSUE THREAD

**Issue by ginward** [Microsoft/EconML#46]
I was wondering if the deepiv pacakge has causal inference built in? For example, in the causal random forest package, a confidence interval can be estimated for the treatment effects. Is there similar functionality here? So far I am only able to see a predicted value for treatment effect, but no standard errors.

**Comment by kbattocchi** [comment]
At the moment we just support bootstrap estimation via our generic `econml.bootstrap.BootstrapEstimator` wrapper, but we're actively considering more elegant per-estimator inference techniques.  Hopefully by the end of the summer we'll have more to say about this.

**Comment by ginward** [comment]
I see @kbattocchi 

So the bootstrap wrapper can be wrapped around the deepiv package as well?

Thanks!

**Comment by ginward** [comment]
Is there a paper/technical analysis on how the bootstrap confidence is calculated? @kbattocchi

**Comment by kbattocchi** [comment]
Yes, the bootstrap wrapper can wrap anything with a `fit` method (pretty much all sklearn models and econml models).

But I should warn you - the way the wrapper works is that it generates a number of bootstrap samples (samples with replacement drawn from the data that is fit against) and then trains a number of cloned instances of whatever model is being wrapped.  In the case of the Deep IV estimator, this requires training multiple neural networks for each cloned instance, so it is very slow.  That's one of the reasons we'd like to pursue estimator-specific techniques that may be less general but more performant.

I'll see if one of our researchers has a good reference for the details of bootstrap estimation that we can add to our documentation.  Thanks for your interest!

**Comment by ginward** [comment]
@kbattocchi The way you describe it makes me think if the bootstrap method you described is also called infinitesimal jackknife as [described in this paper](http://jmlr.org/papers/volume15/wager14a/wager14a.pdf). 

Is it one of the jackknife estimation methods though?

**Comment by kbattocchi** [comment]
No, we're not doing jackknife estimation (we don't track which bootstrap samples are missing each observation, which would be required), at least in the current version of the package.

**Comment by ginward** [comment]
@kbattocchi Thanks for you reply! 

I tried the bootstrap wrapper in `Deep IV Examples.ipynb`, but it gives me some errors: 

`boot_est = BootstrapEstimator(deepIvEst, n_bootstrap_samples=10)
`

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-9-394e4fede66a> in <module>
----> 1 boot_est = BootstrapEstimator(deepIvEst, n_bootstrap_samples=10)

~/Dropbox (Cambridge University)/R301/EconML/econml/bootstrap.py in __init__(self, wrapped, n_bootstrap_samples, n_jobs)
     39 
     40     def __init__(self, wrapped, n_bootstrap_samples=1000, n_jobs=None):
---> 41         self._instances = [clone(wrapped, safe=False) for _ in range(n_bootstrap_samples)]
     42         self._n_bootstrap_samples = n_bootstrap_samples
     43         self._n_jobs = n_jobs

~/Dropbox (Cambridge University)/R301/EconML/econml/bootstrap.py in <listcomp>(.0)
     39 
     40     def __init__(self, wrapped, n_bootstrap_samples=1000, n_jobs=None):
---> 41         self._instances = [clone(wrapped, safe=False) for _ in range(n_bootstrap_samples)]
     42         self._n_bootstrap_samples = n_bootstrap_samples
     43         self._n_jobs = n_jobs

~/anaconda3/lib/python3.6/site-packages/sklearn/base.py in clone(estimator, safe)
     53     elif not hasattr(estimator, 'get_params'):
     54         if not safe:
---> 55             return copy.deepcopy(estimator)
     56         else:
     57             raise TypeError("Cannot clone object '%s' (type %s): "

~/anaconda3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

~/anaconda3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    278     if state is not None:
    279         if deep:
--> 280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
    282             y.__setstate__(state)

~/anaconda3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
    148     copier = _deepcopy_dispatch.get(cls)
    149     if copier:
--> 150         y = copier(x, memo)
    151     else:
    152         try:

~/anaconda3/lib/python3.6/copy.py in _deepcopy_dict(x, memo, deepcopy)
    238     memo[id(x)] = y
    239     for key, value in x.items():
--> 240         y[deepcopy(key, memo)] = deepcopy(value, memo)
    241     return y
    242 d[dict] = _deepcopy_dict

~/anaconda3/lib/python3.6/copy.py in deepcopy(x, memo, _nil)
    178                     y = x
    179                 else:
--> 180                     y = _reconstruct(x, memo, *rv)
    181 
    182     # If is its own copy, don't memoize.

~/anaconda3/lib/python3.6/copy.py in _reconstruct(x, memo, func, args, state, listiter, dictiter, deepcopy)
    280             state = deepcopy(state, memo)
    281         if hasattr(y, '__setstate__'):
--> 282             y.__setstate__(state)
    283         else:
    284             if isinstance(state, tuple) and len(state) == 2:

~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in __setstate__(self, state)
   1264 
   1265     def __setstate__(self, state):
-> 1266         model = saving.unpickle_model(state)
   1267         self.__dict__.update(model.__dict__)
   1268 

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in unpickle_model(state)
    433 def unpickle_model(state):
    434     f = h5dict(state, mode='r')
--> 435     return _deserialize_model(f)
    436 
    437 

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in _deserialize_model(f, custom_objects, compile)
    223         raise ValueError('No model found in config.')
    224     model_config = json.loads(model_config.decode('utf-8'))
--> 225     model = model_from_config(model_config, custom_objects=custom_objects)
    226     model_weights_group = f['model_weights']
    227 

~/anaconda3/lib/python3.6/site-packages/keras/engine/saving.py in model_from_config(config, custom_objects)
    456                         '`Sequential.from_config(config)`?')
    457     from ..layers import deserialize
--> 458     return deserialize(config, custom_objects=custom_objects)
    459 
    460 

~/anaconda3/lib/python3.6/site-packages/keras/layers/__init__.py in deserialize(config, custom_objects)
     53                                     module_objects=globs,
     54                                     custom_objects=custom_objects,
---> 55                                     printable_module_name='layer')

~/anaconda3/lib/python3.6/site-packages/keras/utils/generic_utils.py in deserialize_keras_object(identifier, module_objects, custom_objects, printable_module_name)
    143                     config['config'],
    144                     custom_objects=dict(list(_GLOBAL_CUSTOM_OBJECTS.items()) +
--> 145                                         list(custom_objects.items())))
    146             with CustomObjectScope(custom_objects):
    147                 return cls.from_config(config['config'])

~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in from_config(cls, config, custom_objects)
   1030                 if layer in unprocessed_nodes:
   1031                     for node_data in unprocessed_nodes.pop(layer):
-> 1032                         process_node(layer, node_data)
   1033 
   1034         name = config.get('name')

~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in process_node(layer, node_data)
    989             # and building the layer if needed.
    990             if input_tensors:
--> 991                 layer(unpack_singleton(input_tensors), **kwargs)
    992 
    993         def process_layer(layer_data):

~/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
    455             # Actually call the layer,
    456             # collecting output(s), mask(s), and shape(s).
--> 457             output = self.call(inputs, **kwargs)
    458             output_mask = self.compute_mask(inputs, previous_mask)
    459 

~/anaconda3/lib/python3.6/site-packages/keras/layers/core.py in call(self, inputs, mask)
    685         if has_arg(self.function, 'mask'):
    686             arguments['mask'] = mask
--> 687         return self.function(inputs, **arguments)
    688 
    689     def compute_mask(self, inputs, mask=None):

~/anaconda3/lib/python3.6/site-packages/keras/layers/core.py in <lambda>(tx)
    358             return K.reshape(all_grads, (-1, d_y, d_t))
    359 
--> 360         self._marginal_effect_model = Model([t_in, x_in], L.Lambda(lambda tx: calc_grad(*tx))([t_in, x_in]))
    361 
    362     def effect(self, T0, T1, X=None):

TypeError: 'str' object is not callable

```

Is there something I did wrong here?

**Comment by ginward** [comment]
> @kbattocchi Thanks for you reply!
> 
> **UPDATE: I updated the code and errors.**
> 
> I tried adding the bootstrap wrapper to the file `Deep IV Examples.ipynb`, but it gives me some errors:
> 
> ```
> deepIvEst = DeepIVEstimator(n_components = 10, # number of gaussians in our mixture density network
>                             m = lambda z, x : treatment_model(keras.layers.concatenate([z,x])), # treatment model
>                             h = lambda t, x : response_model(keras.layers.concatenate([t,x])),  # response model
>                             n_samples = 1, # number of samples to use to estimate the response
>                             use_upper_bound_loss = False, # whether to use an approximation to the true loss
>                             n_gradient_samples = 1, # number of samples to use in second estimate of the response (to make loss estimate unbiased)
>                             optimizer='adam', # Keras optimizer to use for training - see https://keras.io/optimizers/ 
>                             s1=100, # number of epochs to train treatment model
>                             s2=100) # number of epochs to train response model
> boot_est = BootstrapEstimator(deepIvEst, n_bootstrap_samples=100, n_jobs=4)
> boot_est.fit(Y=y,T=t,X=x,Z=z)
> ```
> 
> ```
> [Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-14-2528bf95d3ca> in <module>
> ----> 1 boot_est.fit(Y=y,T=t,X=x,Z=z)
> 
> ~/Dropbox (Cambridge University)/R301/EconML/econml/bootstrap.py in fit(self, *args, **named_args)
>      56         Parallel(n_jobs=self._n_jobs, prefer='threads', verbose=3)(
>      57             (obj.fit, [arg[inds] for arg in args], {arg: named_args[arg][inds] for arg in named_args})
> ---> 58             for obj, inds in zip(self._instances, indices)
>      59         )
>      60         return self
> 
> ~/anaconda3/lib/python3.6/site-packages/joblib-0.13.2-py3.6.egg/joblib/parallel.py in __call__(self, iterable)
>     932 
>     933             with self._backend.retrieval_context():
> --> 934                 self.retrieve()
>     935             # Make sure that we get a last message telling us we are done
>     936             elapsed_time = time.time() - self._start_time
> 
> ~/anaconda3/lib/python3.6/site-packages/joblib-0.13.2-py3.6.egg/joblib/parallel.py in retrieve(self)
>     831             try:
>     832                 if getattr(self._backend, 'supports_timeout', False):
> --> 833                     self._output.extend(job.get(timeout=self.timeout))
>     834                 else:
>     835                     self._output.extend(job.get())
> 
> ~/anaconda3/lib/python3.6/multiprocessing/pool.py in get(self, timeout)
>     642             return self._value
>     643         else:
> --> 644             raise self._value
>     645 
>     646     def _set(self, i, obj):
> 
> ~/anaconda3/lib/python3.6/multiprocessing/pool.py in worker(inqueue, outqueue, initializer, initargs, maxtasks, wrap_exception)
>     117         job, i, func, args, kwds = task
>     118         try:
> --> 119             result = (True, func(*args, **kwds))
>     120         except Exception as e:
>     121             if wrap_exception and func is not _helper_reraises_exception:
> 
> ~/anaconda3/lib/python3.6/site-packages/joblib-0.13.2-py3.6.egg/joblib/_parallel_backends.py in __call__(self, *args, **kwargs)
>     565     def __call__(self, *args, **kwargs):
>     566         try:
> --> 567             return self.func(*args, **kwargs)
>     568         except KeyboardInterrupt:
>     569             # We capture the KeyboardInterrupt and reraise it as
> 
> ~/anaconda3/lib/python3.6/site-packages/joblib-0.13.2-py3.6.egg/joblib/parallel.py in __call__(self)
>     223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
>     224             return [func(*args, **kwargs)
> --> 225                     for func, args, kwargs in self.items]
>     226 
>     227     def __len__(self):
> 
> ~/anaconda3/lib/python3.6/site-packages/joblib-0.13.2-py3.6.egg/joblib/parallel.py in <listcomp>(.0)
>     223         with parallel_backend(self._backend, n_jobs=self._n_jobs):
>     224             return [func(*args, **kwargs)
> --> 225                     for func, args, kwargs in self.items]
>     226 
>     227     def __len__(self):
> 
> ~/Dropbox (Cambridge University)/R301/EconML/econml/deepiv.py in fit(self, Y, T, X, Z)
>     313         n_components = self._n_components
>     314 
> --> 315         treatment_network = self._m(z_in, x_in)
>     316 
>     317         # the dimensionality of the output of the network
> 
> <ipython-input-10-df8c54d69989> in <lambda>(z, x)
>       1 deepIvEst = DeepIVEstimator(n_components = 10, # number of gaussians in our mixture density network
> ----> 2                             m = lambda z, x : treatment_model(keras.layers.concatenate([z,x])), # treatment model
>       3                             h = lambda t, x : response_model(keras.layers.concatenate([t,x])),  # response model
>       4                             n_samples = 1, # number of samples to use to estimate the response
>       5                             use_upper_bound_loss = False, # whether to use an approximation to the true loss
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/engine/base_layer.py in __call__(self, inputs, **kwargs)
>     455             # Actually call the layer,
>     456             # collecting output(s), mask(s), and shape(s).
> --> 457             output = self.call(inputs, **kwargs)
>     458             output_mask = self.compute_mask(inputs, previous_mask)
>     459 
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in call(self, inputs, mask)
>     562             return self._output_tensor_cache[cache_key]
>     563         else:
> --> 564             output_tensors, _, _ = self.run_internal_graph(inputs, masks)
>     565             return output_tensors
>     566 
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/engine/network.py in run_internal_graph(self, inputs, masks)
>     719                                     kwargs['mask'] = computed_mask
>     720                             output_tensors = to_list(
> --> 721                                 layer.call(computed_tensor, **kwargs))
>     722                             output_masks = layer.compute_mask(computed_tensor,
>     723                                                               computed_mask)
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/layers/core.py in call(self, inputs)
>     877 
>     878     def call(self, inputs):
> --> 879         output = K.dot(inputs, self.kernel)
>     880         if self.use_bias:
>     881             output = K.bias_add(output, self.bias, data_format='channels_last')
> 
> ~/anaconda3/lib/python3.6/site-packages/keras/backend/tensorflow_backend.py in dot(x, y)
>    1083         out = tf.sparse_tensor_dense_matmul(x, y)
>    1084     else:
> -> 1085         out = tf.matmul(x, y)
>    1086     return out
>    1087 
> 
> ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py in matmul(a, b, transpose_a, transpose_b, adjoint_a, adjoint_b, a_is_sparse, b_is_sparse, name)
>    2385       are both set to True.
>    2386   """
> -> 2387   with ops.name_scope(name, "MatMul", [a, b]) as name:
>    2388     if transpose_a and adjoint_a:
>    2389       raise ValueError("Only one of transpose_a and adjoint_a can be True.")
> 
> ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in __enter__(self)
>    6081       if self._values is None:
>    6082         self._values = []
> -> 6083       g = _get_graph_from_inputs(self._values)
>    6084       self._g_manager = g.as_default()
>    6085       self._g_manager.__enter__()
> 
> ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _get_graph_from_inputs(op_input_list, graph)
>    5711         graph = graph_element.graph
>    5712       elif original_graph_element is not None:
> -> 5713         _assert_same_graph(original_graph_element, graph_element)
>    5714       elif graph_element.graph is not graph:
>    5715         raise ValueError("%s is not from the passed-in graph." % graph_element)
> 
> ~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in _assert_same_graph(original_item, item)
>    5647   if original_item.graph is not item.graph:
>    5648     raise ValueError("%s must be from the same graph as %s." % (item,
> -> 5649                                                                 original_item))
>    5650 
>    5651 
> 
> ValueError: Tensor("dense_1/kernel:0", shape=(2, 128), dtype=float32_ref) must be from the same graph as Tensor("concatenate_1/concat:0", shape=(?, 2), dtype=float32).
> ```
> 
> Is there something I did wrong here?

This is super weird because I am basically following the documentations ... @kbattocchi

**Comment by ginward** [comment]
Oh it works if I change the n_jobs to 1. Is this a bug?
