### ISSUE TITLE
CausalForestDML.tune() is not parsing pandas dataframes correctly 

### ISSUE THREAD

**Issue by SumaTutta** [microsoft/EconML#461]
CausalForestDML.tune() is returning error when pandas dataframes are passed as parameters for Y, T, X and W. The function works fine when the parameters passed are numpy arrays instead of dataframe. However, this is resulting in follow up error in CausalForestDML.fit(Y, T) when numpy arrays are used - 
 ValueError: Parameter `max_samples` must be in (0, .5], if `inference=True`. Got value 0.5
[Error Message - Tune.txt](https://github.com/microsoft/EconML/files/6452223/Error.Message.-.Tune.txt)
[Follow up Error - Tune.txt](https://github.com/microsoft/EconML/files/6452224/Follow.up.Error.-.Tune.txt)

**Comment by kbattocchi** [comment]
We released version 0.11.0 of the econml package to PyPI this weekend which should address this - could you make sure that you're using the latest version and then retry and report back if you're still having issues?

**Comment by vsyrgkanis** [comment]
@SumaTutta  we fixed the pandas but unfortunately we didn't notice the second issue you raised. We're fixing that too and we'll get a bug fix release this week. 

For now, please specify your own grid in tune and don't use the default. In particular use:
```python
params = {'max_samples': [.3, .45],
                      'min_balancedness_tol': [.3, .5],
                      'min_samples_leaf': [5, 50],
                      'max_depth': [3, None],
                      'min_var_fraction_leaf': [None, .01]}
```

when calling tune.

**Comment by vsyrgkanis** [comment]
@SumaTutta this was actually a weird corner case bug. Weirdly, if you just drop one sample from your dataset I think it will work fine.

**Comment by SumaTutta** [comment]
Thanks Vasilis
