### ISSUE TITLE
Unclear/Incorrect Maths in documentation of OrthoLearner

### ISSUE THREAD

**Issue by finnhacks42** [microsoft/EconML#467]
The documentation on OrthoLearner here https://econml.azurewebsites.net/_autosummary/econml._ortho_learner.html#econml._ortho_learner._OrthoLearner looks like it contains a typo. 

This expression has a double sum over the same index i, which does not make sense to me.
![image](https://user-images.githubusercontent.com/7020741/118204992-ca7fb200-b4a2-11eb-8ed6-cc0eaf10d590.png)

**Comment by kbattocchi** [comment]
Thanks for pointing this out - it will be fixed in our upcoming release.
