### ISSUE TITLE
 'LinearDML' object has no attribute 'shap_values'

### ISSUE THREAD

**Issue by AsmirMumin** [microsoft/EconML#469]
I get the above mentioned AttributeError when trying to get **shap_values** by the shap_values() method from the fitted **LinearDML** object. 

In the **Interpretability with SHAP.ipynb**, that error seem not to appear. 

Anyone knows what´s the issue?

**Comment by kbattocchi** [comment]
Could you say what versions of econml and shap you're using?

**Comment by AsmirMumin** [comment]
@kbattocchi Thanks for commenting. I use econml 0.8.0 and shap 0.37.0. I guess I have to update both packages.
