### ISSUE TITLE
Estimating the outcome Y after fitting given the value of T_test, X_test,W_test

### ISSUE THREAD

**Issue by filippofiocchi** [microsoft/EconML#477]
Hello,

I am using EconML to analyse some data. I was wondering, if given for example a fittet CausalForestDML, there is a way to predict the outcome of Y_test given T_test,X_test,W_test. Is it possible to do it using the package?
Also because,  by reading the documentation, I understood that the score function does something like that.

Thank again for this amazing package.

**Comment by BrianMiner** [comment]
Did you figure it out?

**Comment by filippofiocchi** [comment]
No, but I figure out that they already had a few issues like this one.
Like this one : https://github.com/microsoft/EconML/issues/182 
And the answer is the same, it is not implemented.

**Comment by BrianMiner** [comment]
It seems the answer is to fit any supervised learning model and predict for each observation the expected value of Y for the treatment they actually received (I would think it more efficient to predict for everyone the control t=0) and then use the treatment effects from this package to estimate the expected value of Y for any value of the treatment (given X)

**Comment by vsyrgkanis** [comment]
Its best to train outside a model:
Y ~ X, W
T ~ X, W

then the counterfactual prediction of Y is:

ycntf = E[Y|X,W] + theta(X) * (T - E[T|X,W])

this way you dont gave any covariate ahift problems.

training a model for T=0 has covariate shift problems as that subpopulation can be quite different.

the above way you are essentially predicting a baseline outcome at the “expected treatment” that a person would have received under the observational policy and you avoid covariate shift problems.

ideally also these models would be trained on a separate sample as the sample on which you trained the cate theta(X)

**Comment by BrianMiner** [comment]
To confirm the notation you are using above (I always stumble on it), is this the same as recommended here: https://econml.azurewebsites.net/spec/api.html#linear-in-treatment-cate-estimators

In the below I read this to be advocating training a model outside to predict E[Y | X] (not sure if W is included in X?) and then using the prediction of whatever the person was actual given (T)  as the baseline and adjust it by the relevant tau(t,T,x) to estimate how to adjust the baseline outside prediction to E[Y | t, X] for every value t (not including T which is from the baseline outside model). Is this correct understanding?


![image](https://user-images.githubusercontent.com/8807554/121440907-cf773a80-c956-11eb-9143-b530f825c3d8.png)

**Comment by vsyrgkanis** [comment]
That's a slgithyl different approach that requires knowing what ttreatment the observational policy would assign to this sample. 

The approach I mentioned above does not require such knowledge and imputes it by also learning a propensity model. Moreover, it trains slightly different models to avoid any covariate shift, i.e. trains E[Y | X] and E[T|X] only and not E[Y|T,X]

**Comment by BrianMiner** [comment]
Does this work with discrete treatments?

In your formulation above : ycntf = E[Y|X,W] + theta(X) * (T - E[T|X,W])
is theta (X) the constant marginal cate? I wish i immediately saw the algebra and how this arrives at any E[Y | T,X]
constant marginal CATE

**Comment by vsyrgkanis** [comment]
yeap theta(X) is the const_marginal_cate.

This derivation assumes a constant marginal cate, i.e. E[Y|T,X] = \theta(X)*T + g(X)

but that is also assumed by most of our estimators.

It works for discrete too. Then E[T|X] is the Pr(T=1|X). 

Note that:
E[Y|X] = theta(X) * E[T|X] + g(X)
and 
E[Y|T, X] = theta(X) * (T - E[T|X]) + theta(X) * E[T|X] + g(X) = theta(X) * (T - E[T|X]) + E[Y|X]

So then the idea is to use this last version of the expression to impute a Y.
where you use the ML models for E[T|X] and E[Y|X] and the CATE model for theta(X)

**Comment by DonCorle0ne** [comment]
@vsyrgkanis Thanks for the idea here. Is theta(X) actually a constant here?

**Comment by giheungkim** [comment]
This assumes the outcome is linear in treatment right? So this would not hold for say, NonParamDMLIV method? 

If I want to predict the outcome that is not linear in treatment, how should I proceed? i.e. from something like this:

![Screen Shot 2023-07-08 at 6 57 51 PM](https://github.com/py-why/EconML/assets/17394971/c19573af-42f4-4080-be45-6c157e406d58)

**Comment by xec-rkumar** [comment]
> yeap theta(X) is the const_marginal_cate.
> 
> This derivation assumes a constant marginal cate, i.e. E[Y|T,X] = \theta(X)*T + g(X)
> 
> but that is also assumed by most of our estimators.
> 
> It works for discrete too. Then E[T|X] is the Pr(T=1|X).
> 
> Note that: E[Y|X] = theta(X) * E[T|X] + g(X) and E[Y|T, X] = theta(X) * (T - E[T|X]) + theta(X) * E[T|X] + g(X) = theta(X) * (T - E[T|X]) + E[Y|X]
> 
> So then the idea is to use this last version of the expression to impute a Y. where you use the ML models for E[T|X] and E[Y|X] and the CATE model for theta(X)

Thank you for the clear derivation of the counterfactual prediction. I have a question on the ML models used for E[T|X] and E[Y|X], I understand that you mention they are ML models that you train separately from the CATE model, I am wondering why we can't use the fitted versions of model_y (for E[Y|X]) and model_t (for E[T|X]) that have been fitted by the CATE model already.
