### ISSUE TITLE
SHAP values not working in Double Machine Learning example notebook

### ISSUE THREAD

**Issue by arkadaw9** [microsoft/EconML#503]
While running the [Double Machine Learning example notebook](https://github.com/microsoft/EconML/blob/master/notebooks/Double%20Machine%20Learning%20Examples.ipynb), I am getting the following error message : 
![image](https://user-images.githubusercontent.com/56458648/127400130-ccddde79-74cd-4d13-bdff-b3793bf85572.png)

Could you please help me with this?

The versions I'm currently using are:
```
Python 3.7
Econml 0.11.1
shap 0.37.0
```

**Comment by vsyrgkanis** [comment]
Our package requires shap > 0.38.1
https://github.com/microsoft/EconML/blob/8b0c33aaf509a4c877059abbe573eacf490cbf11/setup.cfg#L42

**Comment by arkadaw9** [comment]
Thanks!! It works.
