### ISSUE TITLE
Why the ate_interval produces same result for different alpha values? 

### ISSUE THREAD

**Issue by ukm5** [microsoft/EconML#511]
Also, to what alpha do the confidence intervals in ate_inference summary correspond to? I was trying to determine the latter using the ate_interval function when I noticed that the intervals returned are independent of alpha passed into the function. 
![same_confidence_interval_LI](https://user-images.githubusercontent.com/51415871/129109583-1d229e0d-c633-4e9e-b20e-90a257f6caaa.jpg)

**Comment by vsyrgkanis** [comment]
I believe this relates to an issue that was recently fixed and merged #476

You could either install from the master branch of the repo or wait for the next release.

**Comment by ukm5** [comment]
Thanks! So just to confirm, the current intervals outputted for CATE and ATE are at 90% confidence? Also, how do I pass an alpha when using the effect_inference function?
Finally, is there an ETA on the next release? Since I work on my company maintained cloud of libraries, I am unsure of how to install from the master branch, but anyways thanks for the info!

**Comment by vsyrgkanis** [comment]
yeap!
you call: effect_inference(X).summary_frame(alpha=..) 
or effect_inference(X).conf_int(alpha=...)
release should happen by Friday.
