### ISSUE TITLE
ValueError: No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed

### ISSUE THREAD

**Issue by OnkarMulay** [microsoft/EconML#517]
Why is this an issue?

I am following from example notebook, but I still get this error.
What is exact/specific requirement?

Code:
import numpy as np
vals= np.abs(shap_values).mean(0)

feature_importance = pd.DataFrame(list(zip(SG_sub.columns, sum(vals))), columns=['col_name','feature_importance_vals'])
feature_importance.sort_values(by=['feature_importance_vals'], ascending=False,inplace=True)
top_features = feature_importance["col_name"]
top_features = [i.split("_")[0] for i in top_features]
top_features

from econml.solutions.causal_analysis import CausalAnalysis

ca = CausalAnalysis(
    top_features,
    categorical=None,
    heterogeneity_inds=None,
    classification=True,
    nuisance_models="automl",
    heterogeneity_model="forest",
    n_jobs=-1)

ca.fit(x_train,y_train.values)

ValueError: No valid specification of the columns. Only a scalar, list or slice of all integers or all strings, or boolean mask is allowed

The top_feature is a list
['ESTAT', 'rstat', 'PA', 'M1']

**Comment by kbattocchi** [comment]
Thanks for the report - could you include the full stack trace, as well as what versions of sklearn and pandas you're using? I don't see anything obviously wrong, but sklearn and pandas have both changed certain aspects of how they do indexing over the last few years.

**Comment by OnkarMulay** [comment]
ca = CausalAnalysis(
top_features,
categorical=None,
heterogeneity_inds=None,
classification=True,
nuisance_models="automl",
heterogeneity_model="forest",
n_jobs=-1)

Here categorical = None is becoming a problem, rather it should be  [] blank list

**Comment by kbattocchi** [comment]
@OnkarMulay Sorry I missed that, but glad you were able to track it down.  If you are using our final 0.12.0 release you ought to see a clearer error message than that.  Are you using one of our betas?  If so I'd recommend upgrading to the final release since we've fixed several bugs.
