### ISSUE TITLE
Error Method fit of OrthoIV

### ISSUE THREAD

**Issue by juandavidgutier** [microsoft/EconML#520]
The method fit of OrthoIV require three parameters: Y, T, Z. However, when the three parameters are given (e.g. any.fit=(Y,T,Z) the error: "fit() takes 3 positional arguments but 4 were given" is showed.

**Comment by vsyrgkanis** [comment]
Z is keyword only. So fit(Y, T, Z=Z)

**Comment by juandavidgutier** [comment]
Thanks  for the clarity
