### ISSUE TITLE
How to save the trained model?

### ISSUE THREAD

**Issue by superpig99** [microsoft/EconML#542]
I wonder how to save the CausalForestDML model and then reuse it? Thanks for your answer!

**Comment by kbattocchi** [comment]
In general, all of our estimators should support serialization via standard python pickling (although this depends on any submodels also supporting this).

**Comment by superpig99** [comment]
Thanks!

**Comment by superpig99** [comment]
Hi, I got a new problem: I want to deploy the trained CausalForestDML model online. One way I learnt is to save the model as the ONNX format, and then use mmlspark to run. But, it seems like that econml class cannot be converted to ONNX? Could you please tell me how to deploy econml model online? Thanks very much!

**Comment by kbattocchi** [comment]
We don't currently support any direct way to convert to ONNX, and unfortunately it looks fairly involved to support (see e.g. https://github.com/onnx/sklearn-onnx/blob/268b2c2163b0dcbb48ca838d4e99c5b3b6749f76/skl2onnx/operator_converters/random_forest.py#L323 for an implementation of converting an sklearn random forest regressor to ONNX).

If converting to ONNX is a hard requirement, then one short term solution could be to create a [`SingleTreeCateInterpreter`](https://econml.azurewebsites.net/_autosummary/econml.cate_interpreter.SingleTreeCateInterpreter.html#econml.cate_interpreter.SingleTreeCateInterpreter), interpret your trained CausalForestDML model with it, and then use the sklearn-onnx library to convert the tree interpreter's `tree_model_` attribute (which will be an sklearn [`DecisionTreeRegressor`](https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeRegressor.html#sklearn.tree.DecisionTreeRegressor)) to ONNX.  But do note that if you go this route, the interpretation of the CausalForestDML model as a decision tree is a lossy process, so this would not be expected to be as accurate as using the initial model directly.

**Comment by superpig99** [comment]
Oh I got it. Thank you very much :)
