### ISSUE TITLE
Pricing use case : Dataset requirements

### ISSUE THREAD

**Issue by drskd** [microsoft/EconML#547]
I am currently using econml in a pricing use case.

In my dataset I have the transactions aggregated by months, indicating which product and how much a customer consumes every month.
If customer 1 buys 10 units of product A in January and 5 in March, I will have something like this : 

| Period| Customer| Product| Quantity |
| ------------- |:-------------:| -----:| -----:|
January |1| A | 10
March |1 | A | 5

Is it ok to leave it as is?

Should I complete the dataset and have an additional row for each period of time without transactions?
I have illustrated my point in the table below.

| Period| Customer| Product| Quantity |
| ------------- |:-------------:| -----:| -----:|
January |1| A | 10
**February**|**1**| **A** |**0**
March |1 | A | 5

**Comment by kbattocchi** [comment]
Yes, I think it would be best to add the missing months; if you're using something like DoubleML, then in the first stage we'll fit price and quantity models and you'd want the quantity model training process to have access to the fact that 0 units were sold in those months, and you'd also want those months to be represented in the second stage when we're using the residuals from those predictions to train the final model.

**Comment by drskd** [comment]
Thanks for your answer !
