### ISSUE TITLE
Question on applying natural logarithm to treatment and demand

### ISSUE THREAD

**Issue by drskd** [microsoft/EconML#553]
Hello, 

I saw that in the [Case Study - Customer Segmentation at An Online Media Company](https://github.com/microsoft/EconML/blob/fb2d1139f6c271d4b9a24d9c6d122d4d0891afb0/notebooks/CustomerScenarios/Case%20Study%20-%20Customer%20Segmentation%20at%20An%20Online%20Media%20Company.ipynb), you take the natural logarithm of the price. 

In my case, I also use CausalForestDML and prices can vary from below 1 to way more. Applying the logarithm function distorts the value distribution of prices, especially for prices below 1 and creates negative treatment values. For the moment, I transform the data by adding a constant of 1 to prices (before applying logarithm) to prevent this as illustrated below.

| Product| Price| log(Price)| **log(Price+1)**|
| ------------- |:-------------:| -----:| -----:|
A|0.1|  -2.302| **0.095**
A|0.5|  -0.693| **0.405**
A|10 | 2.303| **2.398**

I also perform the same modification on the demand values, as the demand can be 0 for some periods.

This felt the most natural way in the situation. What do you think about this modification? Will it have positive, neutral or negative impact on the model estimation? 

I should also mentionned that I have a multi treatment use case where the other treatments are the base treatment raised to different powers. Therefore any change on the base treatment will have an impact on the related polynomial treatments.

**Comment by kbattocchi** [comment]
Economists often think about pricing problems in terms of the [price elasticity of demand](https://en.wikipedia.org/wiki/Price_elasticity_of_demand); when we estimate the effect in the notebook you reference, that is what we are estimating (see the last equation in the Point Elasticity section at the previous link).  Ultimately, though, this is just a modeling approach with one particular economically interpretable treatment effect.

Also keep in mind that however we pre-transform our inputs, DML assumes that there is a linear relationship between the transformed treatment T and the transformed output Y; if the elasticity is not constant (given the features X, in the region of the price curve that we have data for), then taking logs is actually incorrect; likewise, if there is not a linear relationship between the raw prices and quantities then using the untransformed data is incorrect.  So you would ideally know enough about the actual relationship between the prices and quantities to make an appropriate choice of how to transform the data.  What you're doing doesn't sound inherently unreasonable, but you might want to try a few different approaches and see how similar the implications are.

**Comment by drskd** [comment]
Thanks for your answer, clear to me now !
