### ISSUE TITLE
Recomputing the target value

### ISSUE THREAD

**Issue by drskd** [microsoft/EconML#580]
Hi,

Based on issue #378, I would like to compute hypothetical target values based on 10 treatment values and features X (no W features here).

My 2 dimensional treatment is based on the log price and (log price)² :

```
n_T = 10

T = np.reshape(np.linspace(0.1, 1,n_T), (n_T,1))
T_2 = T**2
T_ = np.concatenate((T, T_2),axis=1)
```

Then I get the theta coefficient via a CausalForest (called `estimator`) fitted previously.
`theta_ = estimator.const_marginal_effect(X[0,:]).T`

I then try to compute the part of the target depending on X :

```
model_f_X_ = estimator.models_y[0][-1]
f_X = model_f_X_.predict(X[0,:])

```
I add up all of this to match this formula (without the W features) illustrated below.
![image](https://user-images.githubusercontent.com/34745377/155744564-7b3bb681-e7c4-4596-86b3-98f2f4b5e4c4.png)
```
log_y = np.dot(T_, theta_) + f_X
y = np.exp(log_y)
```
Is this the correct way to do this?
The values produced by the model in `estimator.models_y` seems odd to me. What would be the next steps to correctly check all the computations?

**Comment by kbattocchi** [comment]
Could you elaborate on what about the values in `estimator.models_y` seems odd to you?

It would be helpful if you could post your entire code, but I am surprised you don't get a dimension mismatch based on how you're only using the first row of X - this should be a two-dimensional array even if there's only one row
    > f_X = model_f_X_.predict(X[0,:])
    > theta_ = estimator.const_marginal_effect(X[0,:]).T
 
Other than that, I think that code looks roughly correct, but again having the entire pipeline code available would make it easier to double check.

**Comment by drskd** [comment]
Thanks for your answer!

Here is the full code snippet.

```
index = -1
sample = X.values[index,:].reshape(1,-1)

n_T = 10

T = np.reshape(np.linspace(0.1, 1,n_T), (n_T,1))
T_2 = T**2
T_ = np.concatenate((T, T_2), axis=1)

theta_ = estimator.const_marginal_effect(sample).T
model_f_X_ = estimator.models_y[0][-1]

f_X = model_f_X_.predict(sample)

log_y = np.dot(T_, theta_)+f_X
y = np.exp(log_y)
```

Overall the value of `f_X` seemed odd at first because for all samples the mean is around -5 so it counterbalances a lot the value of `np.dot(T_, theta_)` and the values found in `y` seem low overall. I would expect to have something mostly positive in `f_X` because this is the part of the target value explained by `X`. 
After giving it some thoughts, it makes sense because a lot of of my samples correspond to period with no quantity sold (following issue #547 ). I have put an arbitrary value of 0.001 instead of 0, so the log value of  the target is thus -6.9. I guess the next step would be to find features that help to better discriminate between periods with and without quantity sold. 
Or maybe should I have longer period in order to reduce the occurence of period without quantity?
