### ISSUE TITLE
No module named 'econml.tests' (latest release v0.13.0)

### ISSUE THREAD

**Issue by hanchenresearch** [microsoft/EconML#609]
Hi, I installed the latest Econml using pip install. Wanted to go through the Dynamic DML tutorial, but encountered an error while importing econ.tests. Thank you!

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-5-06659118d379>](https://localhost:8080/#) in <module>()
      3 # Main imports
      4 from econml.dynamic.dml import DynamicDML
----> 5 from econml.tests.dgp import DynamicPanelDGP, add_vlines
      6 
      7 # Helper imports

ModuleNotFoundError: No module named 'econml.tests'

**Comment by kbattocchi** [comment]
Thanks for pointing this out and sorry for the inconvenience.  This was also raised in #588 and I put a workaround there, but we'll update the notebook in a future release to make sure that users can run our notebooks as-is.

**Comment by hanchenresearch** [comment]
Thank you, kbattocchi. I indeed directly run the raw codes.
