### ISSUE TITLE
CausalAnalysis function parameters [Question]

### ISSUE THREAD

**Issue by salman-moh** [microsoft/EconML#618]
The feature_inds parameter are supposed to be only treatment features and categorical are supposed to be non-treatment features that are categorical?

OR

The feature_inds parameter are supposed to contain all features and categorical are supposed to contain all features that are categorical?

I believe feature_inds can take any feature as a treatment so doesnt really matter what we put into it as long as we include the treatment. But what about the categorical parameter?

**Comment by kbattocchi** [comment]
Sorry for the late reply. `categorical` should include all columns in the data that are categorical, whether or not they are also present in `feature_inds`.  `feature_inds` should include all columns that you want to consider as "treatments" to determine a causal effect on the outcome while controlling for the other columns in the dataset.
