### ISSUE TITLE
WeightedModelWrapper issue with linear models with intercept

### ISSUE THREAD

**Issue by vsyrgkanis** [microsoft/EconML#63]
It might be that the weighted model wrapper has a small bug in the case of linear models that fit an intercept:

    def _weighted_inputs(self, X, y, sample_weight):
        normalized_weights = X.shape[0] * sample_weight / np.sum(sample_weight)
        sqrt_weights = np.sqrt(normalized_weights)
        weight_mat = np.diag(sqrt_weights)
        return np.matmul(weight_mat, X), np.matmul(weight_mat, y)

If there is an intercept then we also want the intercept to be multiplied by the weight, so this transformation would be invalid. The user can fix it by augmenting X with an intercept and then calling a linear model without intercept. But this might be cumbersome.

**Comment by kbattocchi** [comment]
I agree that this could be an issue, but it's not clear to me how we might fix it - as far as I can see there's no simple transformation of X and y that will work when fitting a model with an intercept.  Do you have any suggestions?

**Comment by vasilismsr** [comment]
#75  Addressed this.
