### ISSUE TITLE
[Bug] Error with DebiasedLasso and preprocess_data

### ISSUE THREAD

**Issue by drskd** [microsoft/EconML#648]
I saw in your recent commit (#638 ) that you changed something in DebiasedLasso class that has not been pushed to the last version because I have this error when fitting a SparseDML model: 

```
File /anaconda/envs/env_pricing_sks/lib/python3.8/site-packages/econml/sklearn_extensions/linear_model.py:734, in DebiasedLasso.fit(self, X, y, sample_weight, check_input)
    732 super().fit(X, y, sample_weight, check_input)
    733 # Center X, y
--> 734 X, y, X_offset, y_offset, X_scale = self._preprocess_data(
    735     X, y, fit_intercept=self.fit_intercept, normalize=False,
    736     copy=self.copy_X, check_input=check_input, sample_weight=sample_weight, return_mean=True)
    738 # Calculate quantities that will be used later on. Account for centered data
    739 y_pred = self.predict(X) - self.intercept_

AttributeError: 'DebiasedLasso' object has no attribute '_preprocess_data'
```

Do you know when the next version will be released? Can I just make the change of the commit in the mean time?

**Comment by kbattocchi** [comment]
We've just put out the 0.13.1 release - could you check if that fixes your issue?

**Comment by drskd** [comment]
Thanks for the new version, it works fine now when I used DML + Debiased Lasso as the final stage.
I noticed another issue now, I will create a separate one to solve it.
