### ISSUE TITLE
Interpretation of ATE

### ISSUE THREAD

**Issue by juandavidgutier** [microsoft/EconML#667]
Hi @kbattocchi I am new in causal inference analysis, and I am implementing EconML to estimate the ATE and CATE of the treatment: Resource-Constrained Health System Index (RCHSI), which it is a continuous variable with scale from 0 to 1, on the outcome: vaccination rate in municipalities (a binary variable: 0=high vaccination rate, 1=low vaccination rate). I got an ATE=0.37. 

My question is about how I have to interpret this value of 0.37. I am thinking that it could be interpreted as follows: an increase of 1% in the RCHS index of a municipality (e.g. a change from 0.00 to 0.01 in the 0 to 1 scale of the variable) has an average effect of to increase in 0.37%, the probability of that municipality will have a low vaccination rate. However, I am not sure if my interpretation is the correct.
I appreciate a lot your cooperation.

Best regards,

Juan

**Comment by kbattocchi** [comment]
Hi Juan,
Yes, I think that’s the right interpretation. Please feel free to follow up with any other questions.

**Comment by kbattocchi** [comment]
Well, to be more precise I think it’s that going all the way from 0 to 1 would yield a 37% increase on average, but most of our estimators assume that the effect is linear so that basically works out to the same thing.

**Comment by juandavidgutier** [comment]
Thanks a lot @kbattocchi
