### ISSUE TITLE
How to get model reliability/performance from CausalForestDML?

### ISSUE THREAD

**Issue by titubs** [microsoft/EconML#681]
Hello,
I was able to train a causalforest model. However, I am not sure how I can evaluate how good the model is. I plotted my PolicyTree but that does not tell me how reliable the model is, just the splits with the highest heterogenity. 

What are my options? Any advise helps.

@kbattocchi

**Comment by benTC74** [comment]
Hi! @titubs, just wondering what would be your solution to this? I would be interested to know how to tell how good is the model. Thank you!
