### ISSUE TITLE
What is the hypothesis that is being tested which the p-value refers to?

### ISSUE THREAD

**Issue by titubs** [microsoft/EconML#702]

**Comment by kbattocchi** [comment]
I see that this is now closed, but just in case it's helpful the default hypothesis is that the value is equal to zero.  Depending on the scenario, you may be able to get p-values for different target values as well (e.g. see `NormalInferenceResults`'s [`pvalue` method](https://econml.azurewebsites.net/_autosummary/econml.inference.NormalInferenceResults.html#econml.inference.NormalInferenceResults.pvalue))

**Comment by titubs** [comment]
@kbattocchi Hi Keith, thanks for the clarification. Just to ensure I understood, the value being equal to zero is the CATE, right?

**Comment by Leo-T-Zang** [comment]
Hi @kbattocchi ,

I wonder if the value being 0 is for ITE or CATE in case like CausalForestDML(). If it is 0, does it mean no causal Effect?
