### ISSUE TITLE
Issue with semaphore leakage when cloning CausalForestDML estimator

### ISSUE THREAD

**Issue by hila-de-moon** [microsoft/EconML#722]
I am encountering an issue when trying to clone the CausalForestDML estimator in my code. After several iterations of the cloning process, I receive a warning about leaked semaphore objects that need to be cleaned up at shutdown. Despite implementing a try-finally block to properly release the semaphores, the issue persists.

I believe this may be a bug in the econml library, and I would like to raise this issue with you to see if there is a solution. I am happy to provide more information about my code and environment if needed.

Thank you for your time and support!

**Comment by kbattocchi** [comment]
If you can isolate the issue in a small repro that would be ideal, but in the meantime could you provide the output of `pip list` as well as the Python version, operating system, and CPU architecture where you're seeing this?
