### ISSUE TITLE
Make `T0` and `T1` on `effect` keyword-only to avoid confusion

### ISSUE THREAD

**Issue by kbattocchi** [microsoft/EconML#79]
When using inference, it's somewhat ambiguous whether a call like

    est.effect_interval(X, low, high)

uses `low` and `high` as the optional treatments or as the lower and upper bounds of the confidence interval (the first interpretation is correct).

This confusion could be avoided by making `T0` and `T1` into keyword-only arguments, so that the user can call

    est.effect_interval(X)
    est.effect_interval(X, T0=low, T1=high)
    est.effect_interval(X, lower=low, upper=high)

but not

    est.effect_interval(X, low, high)

This would be a breaking change, but the safety benefits probably make it worthwhile anyway.

**Comment by moprescu** [comment]
How does that influence the `effect` function? I.e. would the user still be able to call `effect(x)` and `effect(x, 0, 1)`?

**Comment by vasilismsr** [comment]
it will have to be effect(x, T0=0, T1=1)

**Comment by kbattocchi** [comment]
@moprescu, that is a good question.

The simplest approach would be to apply the same rule to `effect` itself, so that you could call `effect(x)` and `effect(x, T0=0, T1=1)` but not `effect(x, 0, 1)`, although this would be a breaking change which otherwise seems unnecessary (since there's no ambiguity here).

However, if we want the bootstrap wrapper to remain generic, then it's hard to see how to fix `effect_interval` without changing `effect`...

**Comment by kbattocchi** [comment]
@moprescu The changes in #75 will make these arguments keyword-only for `effect_interval` while leaving `effect` untouched by explicitly creating an `effect_interval` method on `BaseCateEstimator`.

**Comment by vasilismsr** [comment]
#75 addresses this
