### ISSUE TITLE
Update documentation, including references

### ISSUE THREAD

**Issue by kbattocchi** [microsoft/EconML#80]
Before our next release we should update our documentation to make sure that it hasn't gotten out of sync with our implementation.

**Comment by tapaswenipathak** [comment]
Hi @kbattocchi, @vasilismsr: Can I work on the ticket or is the ticket internal?

**Comment by kbattocchi** [comment]
@tapaswenipathak Thanks for your interest.  We welcome pull requests from external users (although you'll need to complete a CLA - see https://cla.opensource.microsoft.com/ for details), and if you want to look for places where the documentation and implementation have diverged that would certainly be useful.

However, I think we'll probably also want to perform our own review in any case, just to make sure we are comfortable that any recent additions we've made are fully documented.

**Comment by tapaswenipathak** [comment]
Hi @kbattocchi: Thanks for the response, do you have any planner or task list that you are planning for a finish?

**Comment by kbattocchi** [comment]
@tapaswenipathak If you're speaking generally, then we're using the set of GitHub issues to track self-contained tasks.  We also have some other internal priorities that we haven't put into issues, but those are generally cases which involve large changes to the library or which require specialized knowledge where we wouldn't expect external developers to be able to contribute.

If you meant for documentation issues specifically, then we don't have an organized list - I just filed this issue because we hadn't taken a pass through the documentation lately to make sure that the implementation hadn't drifted from it.  However, since then #85 was filed by another user, which highlights one specific place that should be updated if you want to take that on.

**Comment by kbattocchi** [comment]
Closing as I believe these changes were addressed long ago.
