### ISSUE TITLE
Saving Models Using Pickle: NameError: name 'tf' is not defined

### ISSUE THREAD

**Issue by kivo360** [microsoft/EconML#88]
I'm struggling to save models using pickle. 
The coding example I'm running
```py
import cloudpickle
pickled = cp.dumps(self.deepIvEst)
cp.loads(pickled)
```

I got the error: NameError: name 'tf' is not defined

I get an error that finishes with the exception: `NameError: name 'tf' is not defined`. I added `tf` as a custom object then

```py
File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/layers/__init__.py", line 168, in deserialize
    printable_module_name='layer')
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/utils/generic_utils.py", line 147, in deserialize_keras_object
    list(custom_objects.items())))
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/engine/network.py", line 1062, in from_config
    process_node(layer, node_data)
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/engine/network.py", line 1012, in process_node
    layer(unpack_singleton(input_tensors), **kwargs)
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/keras/layers/core.py", line 716, in call
    return self.function(inputs, **arguments)
  File "/home/***/.local/share/virtualenvs/RayServices-dMeB-KyP/lib/python3.6/site-packages/econml/deepiv.py", line 159, in <lambda>
    samp = L.Lambda(lambda pms: _zero_grad(sample(*pms), pms), output_shape=(d_t,))
NameError: name '_zero_grad' is not defined
```
You may be wondering why I decided to start with the error: NameError: name 'tf' is not defined. 

Well, it's because I wanted to highlight what I think the nature of this problem is. It's a scope issue. Everything that's imported to make the model works isn't used when unpickling a model. The big question is how to make this work? 

One thing I'm thinking of is creating a separate function directly in each estimator that would allow us to reconstruct an entire model by using the hyperparameters and computed gradients, then re-embed them into the rest of the setup.

**Comment by kbattocchi** [comment]
Could you please provide a full repro, as well as the versions of `econml`, `cloudpickle`, `keras`, and `tensorflow` that you're using?  Trying the simplest possible thing that looks like your example seems to work fine on my machine:

    import cloudpickle
    from econml.deepiv import DeepIVEstimator
    import keras

    m = keras.Sequential([keras.layers.Dense(1)])
    h = keras.Sequential([keras.layers.Dense(1)])
    deepIvEst = DeepIVEstimator(1, 
                                lambda z,x: m(keras.layers.concatenate([z,x])), 
                                lambda t,x: h(keras.layers.concatenate([t,x])),
                                1)
    pickled = cloudpickle.dumps(deepIvEst)
    cloudpickle.loads(pickled)

**Comment by kivo360** [comment]
I can. I'll need to isolate the code for a bit. I have no idea why I'm getting this error. It might be a virtualization problem.

**Comment by kivo360** [comment]
Okay, I figured something out. The moment I fit the model I start getting a reference error. There's likely something done after using the tensorflow backend that makes referring to it weird while pickling.

```py
import cloudpickle
from econml.deepiv import DeepIVEstimator
import keras
import numpy as np
treatment_model = keras.Sequential([keras.layers.Dense(128, activation='relu', input_shape=(2,)),
                                    keras.layers.Dropout(0.17),
                                    keras.layers.Dense(64, activation='relu'),
                                    keras.layers.Dropout(0.17),
                                    keras.layers.Dense(32, activation='relu'),
                                    keras.layers.Dropout(0.17)])

response_model = keras.Sequential([keras.layers.Dense(128, activation='relu', input_shape=(2,)),
                                   keras.layers.Dropout(0.17),
                                   keras.layers.Dense(64, activation='relu'),
                                   keras.layers.Dropout(0.17),
                                   keras.layers.Dense(32, activation='relu'),
                                   keras.layers.Dropout(0.17),
                                   keras.layers.Dense(1)])

keras_fit_options = { "epochs": 30,
                      "validation_split": 0.1,
                      "callbacks": [keras.callbacks.EarlyStopping(patience=2, restore_best_weights=True)]}

deepIvEst = DeepIVEstimator(n_components = 10, # number of gaussians in our mixture density network
                            m = lambda z, x : treatment_model(keras.layers.concatenate([z,x])), # treatment model
                            h = lambda t, x : response_model(keras.layers.concatenate([t,x])),  # response model
                            n_samples = 1, # number of samples to use to estimate the response
                            use_upper_bound_loss = False, # whether to use an approximation to the true loss
                            n_gradient_samples = 1, # number of samples to use in second estimate of the response (to make loss estimate unbiased)
                            optimizer='adam', # Keras optimizer to use for training - see https://keras.io/optimizers/ 
                            first_stage_options = keras_fit_options, # options for training treatment model
                            second_stage_options = keras_fit_options) # options for training response model

n = 5000
e = np.random.normal(size=(n,))
x = np.random.uniform(low=0.0, high=10.0, size=(n,))
z = np.random.uniform(low=0.0, high=10.0, size=(n,))
t = np.sqrt((x+2) * z) + e
y = t*t / 10 - x*t / 10 + e

deepIvEst.fit(Y=y,T=t,X=x,Z=z)

pickled = cloudpickle.dumps(deepIvEst)
cloudpickle.loads(pickled)
```

I shouldn't downplay this problem, but one work around I've conjured (personally) is to isolate the trained effect model and pickle that by itself. The same concept doesn't work for the `self.marginal_effect` object, but it does for `self.effect`.

**Comment by kivo360** [comment]
This is a bootleg fix, but here it is.

What I did was overwrite the get and set state objects.  After changing them, I could pickle my file easily and reload the file directly after.

```py
class OverwrittenDeepIVEstimator(DeepIVEstimator):
    def __init__(self, n_components, m, h, n_samples, use_upper_bound_loss=False, n_gradient_samples=0, optimizer='adam', first_stage_options={'epochs':100}, second_stage_options={'epochs':100}):
        super().__init__(n_components, m, h, n_samples, use_upper_bound_loss=use_upper_bound_loss, n_gradient_samples=n_gradient_samples, optimizer=optimizer, first_stage_options=first_stage_options, second_stage_options=second_stage_options)
    
    
    def fit(self, out=None,treat=None,cov=None,instr=None):
        assert out is not None
        assert treat is not None
        assert cov is not None
        assert instr is not None
        super().fit(Y=out,T=treat,X=cov,Z=instr)
    
    def __getstate__(self):
        pickle_params = {
            "n_components": self._n_components,
            "_first_stage_options": {
                "epochs": self._first_stage_options["epochs"],
                "validation_split": self._first_stage_options["validation_split"]
            },
            "_second_stage_options": {
                "epochs": self._first_stage_options["epochs"],
                "validation_split": self._first_stage_options["validation_split"]
            },
            "_n_samples": self._n_samples,
            "_use_upper_bound_loss": self._use_upper_bound_loss,
            "_n_gradient_samples": self._n_gradient_samples,
            "_optimizer": self._optimizer,
            "effect_model": self._effect_model,
            "_d_y": self._d_y
        }
        return pickle_params
    
    def __setstate__(self, item):
        self._n_components = item['n_components']
        self._first_stage_options = {}
        self._second_stage_options = {}

        self._first_stage_options["epochs"] = item['_first_stage_options']['epochs']
        self._first_stage_options["validation_split"] = item['_first_stage_options']['validation_split']

        self._second_stage_options["epochs"] = item['_second_stage_options']['epochs']
        self._second_stage_options["validation_split"] = item['_second_stage_options']['validation_split']

        self._n_samples = item["_n_samples"]
        self._use_upper_bound_loss = item["_use_upper_bound_loss"]
        self._n_gradient_samples = item["_n_gradient_samples"]
        self._optimizer = item["_optimizer"]
        self._effect_model = item["effect_model"]
        self._d_y = item["_d_y"]
```
The test is, as follows:
```py
ivest = OverwrittenDeepIVEstimator(
        n_components = 10, # number of gaussians in our mixture density network
        m = lambda z, x : treatment_model(keras.layers.concatenate([z,x])), # treatment model
        h = lambda t, x : response_model(keras.layers.concatenate([t,x])),  # response model
        n_samples = 1, # number of samples to use to estimate the response
        use_upper_bound_loss = False, # whether to use an approximation to the true loss
        n_gradient_samples = 1, # number of samples to use in second estimate of the response (to make loss estimate unbiased)
        optimizer='adam', # Keras optimizer to use for training - see https://keras.io/optimizers/ 
        first_stage_options = create_callback(), # options for training treatment model
        second_stage_options = create_callback()
    )
    ivest.fit(out=y,treat=t,cov=x,instr=z)
    yay = cp.dumps(ivest)
    model = cp.loads(yay)
```

This doesn't yield any errors, while other methods do.

**Comment by sharpant** [comment]
> Could you please provide a full repro, as well as the versions of `econml`, `cloudpickle`, `keras`, and `tensorflow` that you're using? Trying the simplest possible thing that looks like your example seems to work fine on my machine:
> 
> ```
> import cloudpickle
> from econml.deepiv import DeepIVEstimator
> import keras
> 
> m = keras.Sequential([keras.layers.Dense(1)])
> h = keras.Sequential([keras.layers.Dense(1)])
> deepIvEst = DeepIVEstimator(1, 
>                             lambda z,x: m(keras.layers.concatenate([z,x])), 
>                             lambda t,x: h(keras.layers.concatenate([t,x])),
>                             1)
> pickled = cloudpickle.dumps(deepIvEst)
> cloudpickle.loads(pickled)
> ```

@kbattocchi : Which version of cloudpickle, econml, keras and python were you using on your machine? I am facing the same problem on my machine and I am experimenting with different versions of these packages. Thank you so much!

**Comment by liuyxmax** [comment]
> @kivo360 Your solution works for me - thanks! However, when I add the following additional items in getstate and setstate to uncover the marginal effect, I get an error when running `cloudpickle.loads(pickled)`.
> 
> getstate : `"marginal_effect_model": self._marginal_effect_model` setstate: `self._marginal_effect_model = item["marginal_effect_model"]`
> 
> The error is
> 
> ```
> --> 382         self._marginal_effect_model = Model([t_in, x_in], L.Lambda(lambda tx: calc_grad(*tx))([t_in, x_in]))
>     383 
>     384     def effect(self, X=None, T0=0, T1=1):
> 
> TypeError: 'str' object is not callable
> ```
> I got the same problem. I tried to use econml=0.4 which is release before August 2019. However,  the error still exists. If I do not call fit method, it will not have the error.
> Do you have ideas on how to overcome this? Thank you!
