### ISSUE TITLE
Enable a greater variety of bootstrap estimates

### ISSUE THREAD

**Issue by kbattocchi** [microsoft/EconML#89]
As @vasilismsr pointed out in his review of #75, we are currently using percentile rather than pivot bootstrap intervals.  We should implement pivot intervals as the default instead, and consider adding additional methods (e.g. bootstrap t-intervals as described in https://web.as.uky.edu/statistics/users/pbreheny/621/F12/notes/9-18.pdf)

**Comment by vasilismsr** [comment]
Another important addition to the greater variety would be subsampling without replacement (see #184)
